routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => true,'login' => true]);

Route::get('policy', 'frontend\HomeController@policy');

Route::get('/','frontend\HomeController@index');
Route::get('/home','frontend\HomeController@index')->name('home');

Route::get('/contact', 'frontend\ContactController@index');
Route::resource('/contactus', 'MsgcontactController');

Route::get('/register','frontend\AuthController@register')->name('register');
Route::get('/login','frontend\AuthController@login')->name('login');


Route::get('/profile','frontend\MemberController@profile')->name('profile');
Route::post('/editProfile','frontend\MemberController@editProfile')->name('editProfile');
Route::get('/courseme','frontend\MemberController@courseme');
Route::get('/myorder','frontend\MemberController@myorder');

//Route::get('/notice-payment/{order_id}', 'frontend\NoticePaymentController@index');
Route::post('/createNewNotice','frontend\NoticePaymentController@createNewNotice');

Route::post('/checkCourseMember','frontend\CheckCourseController@checkCourseMember');

Route::get('/course','frontend\ProductController@courseAll');


Route::post('/addCourseFree','frontend\AddCourseController@addCourseFree');
Route::post('/buyCourse','frontend\AddCourseController@buyCourse')->name('buyCourse');


//Socail login
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/courses/section/{product_id}/{id?}/','frontend\CourseVideoController@seeVideo');

Route::post('/callback/payment','frontend\CallBackApiController@callbackApiPayment');


//Guzzle From Getbiz.co
Route::get('/getcourse','frontend\CallBackApiController@guzzleGetCourses');
Route::get('/getcoursePromotion','frontend\CallBackApiController@guzzleGetCoursesPromotion');
Route::get('/getcourseFree','frontend\CallBackApiController@guzzleGetCoursesFree');
Route::get('/getcourseReccomment','frontend\CallBackApiController@guzzleGetCoursesReccomment');

Route::get('/getteachers','frontend\CallBackApiController@guzzleGetTeachers');

Route::prefix('admin')->name('admin.')->group(function()
{
    /** Admin **/
    Route::get('/', function () {
        if(session('adminlogin')){
            return redirect('admin/products');
        }else{
            return view('admin.login');
        }
    });
    
    Route::get('/blank','admin\AdminController@blank');

    
    
    Route::post('/checklogin', 'admin\AdminController@checkLogin');

    Route::get('/logout', 'admin\AdminController@logout');
    
    Route::middleware(['chkadmin'])->group(function () {   
        
        Route::resource('/setting','admin\WebSettingController');
        Route::get('/contact','admin\ContactController@index');
        
         //Aboutus 
         Route::get('/aboutus','admin\AboutusController@index');
         Route::post('/aboutus/updateabout','admin\AboutusController@updateaboutus');
         
        //Slide and banner   
        Route::get('/slideshow','admin\SlidebannerController@slideshow');
        Route::post('/addslideshow','admin\SlidebannerController@addSlideshow');
        Route::post('/updateslideshow','admin\SlidebannerController@updateSlideshow');
        Route::post('/deleteSlideshow','admin\SlidebannerController@deleteSlideshow');


        //Product
        Route::resource('/products','admin\ProductsController');
        Route::post('/products/destroy','admin\ProductsController@destroy');
        Route::post('/products/deletetags', 'admin\ProductsController@deletetags');
        Route::get('/seeMemberCourse/{id}', 'admin\ProductsController@seeMemberCourse');
        Route::get('/seeMemberCourseAll/{id}', 'admin\ProductsController@seeMemberCourseAll');
        
        //category
        Route::get('/categoryproductall','admin\CategoryProductController@categoryProductAll');
        Route::post('/create-categoryproduct','admin\CategoryProductController@createCategory');
        Route::post('/edit-categoryproduct','admin\CategoryProductController@editCategory');
        Route::post('/delete-categoryproduct','admin\CategoryProductController@deleteCategory');



        Route::resource('/teacher','admin\TeacherController');
        Route::post('/teacher/destroy','admin\TeacherController@destroy');
        Route::post('/teacher/deleteexperience', 'admin\TeacherController@deleteExperience');
        Route::post('/teacher/deleteportfolio', 'admin\TeacherController@deletePortfolio');


        // Section and Lecture Course
        Route::get('/curriculum/{id}','admin\SectionController@curriculum')->name('curriculum');


        Route::resource('/section','admin\SectionController');
        Route::post('/section/destroy','admin\SectionController@destroy');
        Route::post('/section/sortSection','admin\SectionController@sortSection');

        Route::resource('/lecture','admin\LectureController');
        Route::post('/lecture/destroy','admin\LectureController@destroy');
        Route::post('/lecture/sortLecture','admin\LectureController@sortLecture');

        // Bank
        Route::resource('bank', 'admin\BankController');
        Route::post('bank/delete', 'admin\BankController@destroy');
    

        Route::get('/curriculum', function () {
            return view('admin.curriculum.curriculum');
        });

        
        Route::resource('memberall','admin\MemberallController');

        Route::get('orderall', 'admin\OrderController@index');
        Route::post('order/delete', 'admin\OrderController@delete');
        Route::get('confirmpayment/{status}/{id}', 'admin\OrderController@confirmpayment');
        Route::get('showorderlist/{id}', 'admin\OrderController@showorderlist')->name('showorderlist');


    });
});

Route::get('/{slug}', 'frontend\ProductController@detail')->name('product_detail.show');

app/Http/Controllers/frontend/AddCourseController.php
<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\MemberCourse;
use Auth;
use Anam\Phpcart\Cart;
use App\Products;
use App\OrderListModel;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use App\Http\Controllers\MailController as MailController;


class AddCourseController extends Controller
{
    function addCourseFree(Request $request){
        $userid = Auth::id();
        
        $checkHaveCourseMember = MemberCourse::where('member_id', $userid) ->where('product_id', $request->course_id)->first();

        if($checkHaveCourseMember == null){
       // dd($checkHaveCourseMember);
        $MemberCourse = new MemberCourse;
        $MemberCourse->member_id = $userid;
        $MemberCourse->product_id = $request->course_id;
        $MemberCourse->status_buy_course = 1;
        $MemberCourse->seq = 1;
        $MemberCourse->save();
        $response= array(
            'status' => 'success',
          );
        return \Response::json($response);
        
        }
    }

    function buyCourse(Request $request){
        $userid = Auth::id();
        $product = Products::find($request->product_id);
      

       // Save profile member
       $this->validate($request, [
        'email' => [
        'required',
              Rule::unique('users')->ignore(Auth::user()->id),
          ],
       ]);

       $member = User::find($userid);
       $member->name = $request->name;
       $member->email = $request->email;
       $member->tel = $request->tel;
       $member->save();

    //     // add to cart
    //     $cart = new Cart();
    //     $cart->setCart('course');
    //     $cart->add([
    //         'id'       => $product->id,
    //         'name'     => $product->tc_namecourse,
    //         'quantity' => 1,
    //         'price'    => $product->tc_discount
    //     ]);

    //   $db = new OrderListModel;
    //   $db->member_id =  $userid;
    //   $db->order_id = "ORD_".time();
    //   $db->order_item = serialize($cart->getItems());
    //   $db->order_totalqty = $cart->totalQuantity();
    //   $db->order_totalall = $cart->getTotal();
    //   $db->order_status = "waiting";
    //   $db->save();
    //   $insert_id = $db->id;
    //   $i= 1;
    //   foreach ($cart->getItems() as $key => $value) {

    //     DB::table('member_course')->insert([
    //       'member_id' => Auth::user()->id,
    //       'order_id' => $insert_id,
    //       'product_id' => $value->id,
    //       'seq' => $i,
    //       "created_at" =>  \Carbon\Carbon::now(),
    //       "updated_at" => \Carbon\Carbon::now(),
    //     ]);
    //     $i++;
    //   }
    //   $cart->clear();

    $insert_id_orderlist = $this->addToOrder($product,$userid,$status_order="waiting");
    
    $sendDataToMail = new MailController;
    $sendDataToMail->sendMailByCourse($insert_id_orderlist);
    
    // dd($cart->getItems());

    return redirect('/myorder');
    
    }

    function addToOrder($product,$userid,$status_order){
            // add to cart
        $cart = new Cart();
        $cart->setCart('course');
        $cart->add([
            'id'       => $product->id,
            'name'     => $product->tc_namecourse,
            'quantity' => 1,
            'price'    => $product->tc_discount
        ]);
  
        $db = new OrderListModel;
        $db->member_id =  $userid;
        $db->order_id = "ORD_".time();
        $db->order_item = serialize($cart->getItems());
        $db->order_totalqty = $cart->totalQuantity();
        $db->order_totalall = $cart->getTotal();
        $db->order_status = $status_order;
        $db->save();
        $insert_id = $db->id;
        $i= 1;

        foreach ($cart->getItems() as $key => $value) {
  
          DB::table('member_course')->insert([
            'member_id' => $userid,
            'order_id' => $insert_id,
            'product_id' => $value->id,
            'seq' => $i,
            'status_buy_course' => ($status_order == "waiting" ? 0 : 1),
            "created_at" =>  \Carbon\Carbon::now(),
            "updated_at" => \Carbon\Carbon::now(),
          ]);
          $i++;
        }
        $cart->clear();


        return $insert_id;
    }
}

app/Http/Controllers/frontend/AuthController.php
<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AuthController extends Controller
{
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    function register(){
        return view('frontend.auth.register');
    }

    function login(){
        return view('frontend.auth.login');
    }


}

app/Http/Controllers/frontend/CheckCourseController.php
<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\MemberCourse;

class CheckCourseController extends Controller
{
    function checkCourseMember(Request $request){
        //dd(Auth::id());
        $MemberCourse = new MemberCourse;
        $id = $request->data;
        $user = Auth::id();
        $getCheckCourseMember = $MemberCourse->checkCourseMember($user,$id);
       // dd($getCheckCourseMember);

        if($getCheckCourseMember == null){
            $response= array(
                'status' => 'failed',
              );
            return \Response::json($response);
        }else{
            if($getCheckCourseMember->status_buy_course == 1){
                $response= array(
                    'status' => 'success',
                );
                return \Response::json($response);
            }else{
                $response= array(
                    'status' => 'pending',
                );
                return \Response::json($response);
            }
        }
        
    }

    
}

app/Http/Controllers/frontend/ContactController.php
<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\ContactModel;
use App\WebSetting;

class ContactController extends Controller
{
    function index(){
      $data['setting'] = WebSetting::get()->first();

      return view('frontend.contact',$data);
    }


    function messageFormto_admin(Request $request){
      
        $db = new ContactModel;
        $db->name = $request->name;
        $db->email = $request->email;
        $db->tel = $request->tel;
        $db->title = $request->title;
        $db->message = $request->message;
        $db->save();

        return redirect('/contact')->with('msg','ส่งข้อความเรียบร้อย');
    }
}

app/Http/Controllers/frontend/CourseVideoController.php
<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Products;
use App\Category;
use App\Teacher;
use App\Section;
use App\Lecture;
class CourseVideoController extends Controller
{
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }
    function seeVideo($product_id,$id=null){

        if($id == ""){
            $section_first = Section::where('sec_product_id',$product_id)->orderBy('sec_sequence', 'asc')->first();
            $data['lecture_find'] = Lecture::where('lecture_section_id',$section_first->id)->orderBy('lecture_sequence', 'asc')->first();
          
        }else{
            $data['lecture_find'] = Lecture::find($id);
        }

        $data['sections'] = Section::where('sec_product_id',$product_id)->orderBy('sec_sequence', 'asc')->get();

        $product = new Products;
        $data['product']= $product->ProductsById($product_id);
     
        return view('frontend.course_video.show_video',$data);
    }
}

app/Http/Controllers/frontend/HomeController.php
<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Slideshow;
use App\Teacher;
use App\Category;
use App\Products;
use Cohensive\Embed\Embed;
use Illuminate\Support\Facades\DB;

class HomeController extends Controller
{
    function index(){

        $count = new Products;
        $data['slideshows'] = Slideshow::all();
        $data['teachers'] = Teacher::all();
        $data['categorys'] = Category::all();
      //  $data['products'] = Products::orderByRaw('id', 'DESC')->where('tc_status', 0)->get();
        $data['products'] = $count->ProductsPromotion();

        return view('frontend.home',$data);
    }

    function policy(){
        echo 'policy';
      }


  
}

app/Http/Controllers/frontend/MemberController.php
<?php

namespace App\Http\Controllers\frontend;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

use App\Http\Controllers\Controller;
use Auth;
use App\MemberCourse;
use App\User;
use App\Products;
use App\OrderListModel;
use App\Teacher;
use App\BankModel;

class MemberController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    function profile(){
        $userid = Auth::id();
       
        if($userid != null){
           $data['member'] = User::find($userid);
        }

        return view('frontend.member.profile',$data);

    }

    function editProfile(Request $request){

        $this->validate($request, [
            'email' => [
            'required',
                  Rule::unique('users')->ignore(Auth::user()->id),
              ],
        ]);
        $userid = Auth::id();
       // Save profile member
        $member = User::find($userid);
        $member->name = $request->name;
        $member->email = $request->email;
        $member->tel = $request->tel;
        $member->save();
        return redirect(url()->previous())->with('msg','แก้ประวัติส่วนตัวเรียบร้อย');
    }

    function courseme(){
        $userid = Auth::id();
        $count = new Products;
        $data['countSection'] = $count->countSection();
        
        $data['orderlists'] = OrderListModel::where('member_id',$userid)->get();
        $MemberCourse = MemberCourse::where([['member_id',$userid],['status_buy_course','=', '1']])->get();
        $courseme = array();
        $data['teachers'] = Teacher::all();
            foreach($MemberCourse as $value){
               // $courseme[] = $count->ProductsById($value->product_id);
               $courseme[] = Products::find($value->product_id);
            }
       
        $data['course'] = array_filter($courseme);
       
       return view('frontend.member.coursemember',$data);

    }

    function myorder(){
        $userid = Auth::id();
        $data['account_pay'] = BankModel::all();
        $data['products'] = Products::all();
        $data['orderlists'] = OrderListModel::where('member_id',$userid)->get();
        return view('frontend.member.myorder',$data);
    }
}

resources/views/frontend/_formcontact.blade.php
<form action="{{ route('contactus.store')}}" class="py-4" method="post">
    @csrf
    <div class="form-group">
        <input type="text" class="form-control" placeholder="ชื่อ-นามสกุล" name="name" required>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="เบอร์โทรศัพท์" name="tel">
    </div>
    <div class="form-group">
        <input type="email" class="form-control" placeholder="อีเมล" name="email" required>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="หัวข้อ" name="title">
    </div>
    <div class="form-group">
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="description"
            placeholder="รายละเอียด"></textarea>
    </div>
    <div class="form-group">
        <label for="captcha">Captcha</label>
        {!! NoCaptcha::display() !!}
        @if ($errors->has('g-recaptcha-response'))
        <span class="help-block">
            <strong class="text-danger">{{ $errors->first('g-recaptcha-response') }}</strong>
        </span>
        @endif
    </div>
    <button type="submit" class="btn  bg-grey">ยืนยันส่ง</button>
</form>

resources/views/frontend/aboutus.blade.php
@extends('frontend.layout.main')



@section('content')

<section id="about-page">
    <div class="bg-top"></div>
    <div class="bg-global">
        <div class="container py-5">
            <div class="row">
                <div class="col-12">
                    @if(!empty($aboutus->picture))
                    <img src="{{ URL::asset($aboutus->picture)}}" class="img-fluid pb-5" alt="">
                    @endif
                    @if(!empty($aboutus->description))
                    {!! $aboutus->description !!}
                    @endif
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/frontend/confirmpayment.blade.php
@extends('frontend.layout.main')



@section('content')

<section id="blog-herb">
    <div class="container">
        <div class="row">
            <div class="col-12  pt-4">

                <h3 class="color-sky">แจ้งการชำระเงิน</h3>
                <!-- <p><strong>Line id : </strong>
                    <a href="http://line.me/ti/p/{{ $keys_global->line_id }}">{{ $keys_global->line_id}}</a>
                </p>
                <a href="http://line.me/ti/p/{{ $keys_global->line_id }}"><img
                        src="{{URL::asset($keys_global->line_qrcode)}}" class="img-fluid py-3" alt="">
                </a> -->
            </div>
        </div>
    </div>
</section>

<section class="py-4">
    <div class="container">
        <div class="row py-4">

            <div class="col-lg-9  col-12">

                <form action="{{ url('createNewNotice') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-4 col-form-label">บัญชีที่โอนเงิน <span
                                class="text-danger">*</span></label>
                        <div class="col-sm-8">
                            @foreach($account_pay as $key=> $value)
                            <div class="form-check pb-3">
                                <input class="form-check-input" type="radio" name="bank_name"
                                    value="{{$value->bank_name}}" required {{( $key == 0 ? "checked" : "" )}}>
                                <label class="form-check-label" for="exampleRadios1">
                                    <span class="pr-3"><img src="{{URL::asset($value->picture)}}" width="35px" alt="">
                                    </span>
                                    <span class="pr-3">{{$value->name_owner}} </span>
                                    <span class="pr-3">{{$value->bank_name}} </span>
                                    <span class="pr-3">{{$value->bank_branch}}</span>
                                    <span class="pr-3">{{$value->account_number}}</span>
                                </label>
                            </div>
                            @endforeach
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="staticEmail" class="col-sm-4 col-form-label">เลขที่ใบสั่งซื้อ <span
                                class="text-danger">*</span> </label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" placeholder="ORD_12345678"
                                value="{{ !empty($order_id) ? $order_id : ""  }}" name="order_id" required>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputPassword" class="col-sm-4 col-form-label">วันที่ชำระเงิน <span
                                class="text-danger">*</span></label>
                        <div class="col-sm-8">
                            <input type="date" class="form-control" placeholder="" name="date_pay" required>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputPassword" class="col-sm-4 col-form-label">เวลา(ระบุโดยประมาณ) <span
                                class="text-danger">*</span></label>
                        <div class="col-sm-8">
                            <input type="time" class="form-control" placeholder="" name="time_pay" required>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="inputPassword" class="col-sm-4 col-form-label">จำนวนเงิน <span
                                class="text-danger">*</span></label>
                        <div class="col-sm-8">
                            <input type="number" class="form-control" placeholder="จำนวนเงิน..1234" name="amount"
                                required>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">หลักฐานการโอนเงิน <span
                                class="text-danger">*</span></label>
                        <div class="col-sm-8">
                            <input type="file" class="form-control-file" id="chooseFile" name="chooseFile" required>
                            <img class="img-fluid" id="blah" src="" />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">รายละเอียดอื่นๆ </label>
                        <div class="col-sm-8">
                            <textarea rows="4" type="text" class="form-control" name="description"
                                placeholder="รายละเอียดการโอนเงิน..."></textarea>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">ชื่อผู้แจ้งการชำระเงิน </label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" placeholder="" name="member_name"
                                value="{{ !empty($member->name) ? $member->name : ""  }}" required>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">อีเมล </label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control" placeholder="email@example.com"
                                value="{{ !empty($member->email) ? $member->email : ""  }}" required name="email">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">เบอร์ติดต่อ </label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" placeholder="081-123-4567"
                                value="{{ !empty($member->tel) ? $member->tel : ""  }}" name="tel" required>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-success mt-5">แจ้งการชำระเงิน</button>
                </form>
            </div>
        </div>
    </div>
</section>
@endsection


@section('script')
<script type="text/javascript">
function readURL(input) {

    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function(e) {
            $('#img_old').hide();
            $('#blah').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
$("#chooseFile").change(function() {
    readURL(this);
});
$('#chooseFile').bind('change', function() {
    var filename = $("#chooseFile").val();
    if (/^\s*$/.test(filename)) {
        $(".file-upload").removeClass('active');
        $("#noFile").text("No file chosen...");
    } else {
        $(".file-upload").addClass('active');
        $("#noFile").text(filename.replace("C:\\fakepath\\", ""));
    }
});
</script>
@endsection

resources/views/frontend/contact.blade.php
@extends('frontend.layout.main')



@section('content')

<section id="contact_page">

    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-12 contact-address">
                @if($keys_global->name_office != "")
                <h1 class="py-4 color-sky">
                    <strong>{{ $keys_global->name_office}}</strong>
                </h1>
                @endif
                @if($keys_global->address != "")
                <p class="pb-3">
                    <strong>ที่อยู่ </strong>{{ $keys_global->address}}
                </p>
                @endif
                @if($keys_global->tel != "")
                <p>
                    <strong> โทร : </strong>
                    <a href="tel: {{ $keys_global->tel}}">{{ $keys_global->tel}}</a>
                </p>
                @endif

                <p><strong>เว็บไซต์ : </strong><a href="{{  url('/')}}">{{  url('/')}}</a></p>

                @if($keys_global->email != "")
                <p>
                    <strong>อีเมล : </strong>{{ $keys_global->email}}
                </p>
                @endif
                @if($keys_global->facebook_page != "")
                <p>
                    <strong>Facebook :</strong>
                    <a href="https://{{ $keys_global->facebook_page}}">
                        {{ $keys_global->facebook_page}}
                    </a>
                </p>
                @endif

                @if($keys_global->line_id != "")
                <p>
                    <strong>Line id : </strong>
                    <a href="http://line.me/ti/p/{{ $keys_global->line_id }}">
                        {{ $keys_global->line_id}}
                    </a>
                </p>
                @endif
                <a href="http://line.me/ti/p/{{ $keys_global->line_id }}">
                    <img src="{{URL::asset($keys_global->line_qrcode)}}" class="img-fluid py-3" alt="">
                </a>
            </div>
            <div class="col-lg-6 col-12" id="contact_success">
                @if(session('msg'))
                <div class="alert alert-success" role="alert">
                    <p>{{session('msg')}}</p>
                </div>
                @endif

                @include('frontend._formcontact')
            </div>
        </div>
    </div>
</section>

@ENDSECTION


@section('script')


@endsection

resources/views/frontend/service.blade.php
@extends('frontend.layout.main')



@section('content')

<section id="service-page">
    <div class="bg-top"></div>
    <div class="bg-global">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-12 col-12 pb-5">
                    <h3 class="color-sky">บริการของเรา</h3>
                </div>

                <div class="col-lg-7 col-12">

                    @if(!empty($service->picture))
                    <img src="{{ URL::asset($service->picture)}}" class="img-fluid pb-5" alt="">
                    @endif
                    @if(!empty($service->description))
                    {!! $service->description !!}
                    @endif
                </div>
                <div class="col-lg-5 col-12">
                    @if(!empty($service->video))
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ $service->video }}"
                            allowfullscreen></iframe>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</section>
@endsection