routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => true,'login' => true]);

Route::get('policy', 'frontend\HomeController@policy');

Route::get('/','frontend\HomeController@index');
Route::get('/home','frontend\HomeController@index')->name('home');

Route::get('/contact', 'frontend\ContactController@index');
Route::resource('/contactus', 'MsgcontactController');

Route::get('/register','frontend\AuthController@register')->name('register');
Route::get('/login','frontend\AuthController@login')->name('login');


Route::get('/profile','frontend\MemberController@profile')->name('profile');
Route::post('/editProfile','frontend\MemberController@editProfile')->name('editProfile');
Route::get('/courseme','frontend\MemberController@courseme');
Route::get('/myorder','frontend\MemberController@myorder');

//Route::get('/notice-payment/{order_id}', 'frontend\NoticePaymentController@index');
Route::post('/createNewNotice','frontend\NoticePaymentController@createNewNotice');

Route::post('/checkCourseMember','frontend\CheckCourseController@checkCourseMember');

Route::get('/course','frontend\ProductController@courseAll');


Route::post('/addCourseFree','frontend\AddCourseController@addCourseFree');
Route::post('/buyCourse','frontend\AddCourseController@buyCourse')->name('buyCourse');


//Socail login
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/courses/section/{product_id}/{id?}/','frontend\CourseVideoController@seeVideo');

Route::post('/callback/payment','frontend\CallBackApiController@callbackApiPayment');


//Guzzle From Getbiz.co
Route::get('/getcourse','frontend\CallBackApiController@guzzleGetCourses');
Route::get('/getcoursePromotion','frontend\CallBackApiController@guzzleGetCoursesPromotion');
Route::get('/getcourseFree','frontend\CallBackApiController@guzzleGetCoursesFree');
Route::get('/getcourseReccomment','frontend\CallBackApiController@guzzleGetCoursesReccomment');

Route::get('/getteachers','frontend\CallBackApiController@guzzleGetTeachers');

Route::prefix('admin')->name('admin.')->group(function()
{
    /** Admin **/
    Route::get('/', function () {
        if(session('adminlogin')){
            return redirect('admin/products');
        }else{
            return view('admin.login');
        }
    });
    
    Route::get('/blank','admin\AdminController@blank');

    
    
    Route::post('/checklogin', 'admin\AdminController@checkLogin');

    Route::get('/logout', 'admin\AdminController@logout');
    
    Route::middleware(['chkadmin'])->group(function () {   
        
        Route::resource('/setting','admin\WebSettingController');
        Route::get('/contact','admin\ContactController@index');
        
         //Aboutus 
         Route::get('/aboutus','admin\AboutusController@index');
         Route::post('/aboutus/updateabout','admin\AboutusController@updateaboutus');
         
        //Slide and banner   
        Route::get('/slideshow','admin\SlidebannerController@slideshow');
        Route::post('/addslideshow','admin\SlidebannerController@addSlideshow');
        Route::post('/updateslideshow','admin\SlidebannerController@updateSlideshow');
        Route::post('/deleteSlideshow','admin\SlidebannerController@deleteSlideshow');


        //Product
        Route::resource('/products','admin\ProductsController');
        Route::post('/products/destroy','admin\ProductsController@destroy');
        Route::post('/products/deletetags', 'admin\ProductsController@deletetags');
        Route::get('/seeMemberCourse/{id}', 'admin\ProductsController@seeMemberCourse');
        Route::get('/seeMemberCourseAll/{id}', 'admin\ProductsController@seeMemberCourseAll');
        
        //category
        Route::get('/categoryproductall','admin\CategoryProductController@categoryProductAll');
        Route::post('/create-categoryproduct','admin\CategoryProductController@createCategory');
        Route::post('/edit-categoryproduct','admin\CategoryProductController@editCategory');
        Route::post('/delete-categoryproduct','admin\CategoryProductController@deleteCategory');



        Route::resource('/teacher','admin\TeacherController');
        Route::post('/teacher/destroy','admin\TeacherController@destroy');
        Route::post('/teacher/deleteexperience', 'admin\TeacherController@deleteExperience');
        Route::post('/teacher/deleteportfolio', 'admin\TeacherController@deletePortfolio');


        // Section and Lecture Course
        Route::get('/curriculum/{id}','admin\SectionController@curriculum')->name('curriculum');


        Route::resource('/section','admin\SectionController');
        Route::post('/section/destroy','admin\SectionController@destroy');
        Route::post('/section/sortSection','admin\SectionController@sortSection');

        Route::resource('/lecture','admin\LectureController');
        Route::post('/lecture/destroy','admin\LectureController@destroy');
        Route::post('/lecture/sortLecture','admin\LectureController@sortLecture');

        // Bank
        Route::resource('bank', 'admin\BankController');
        Route::post('bank/delete', 'admin\BankController@destroy');
    

        Route::get('/curriculum', function () {
            return view('admin.curriculum.curriculum');
        });

        
        Route::resource('memberall','admin\MemberallController');

        Route::get('orderall', 'admin\OrderController@index');
        Route::post('order/delete', 'admin\OrderController@delete');
        Route::get('confirmpayment/{status}/{id}', 'admin\OrderController@confirmpayment');
        Route::get('showorderlist/{id}', 'admin\OrderController@showorderlist')->name('showorderlist');


    });
});

Route::get('/{slug}', 'frontend\ProductController@detail')->name('product_detail.show');

resources/views/admin/curriculum/curriculum.blade.php
@extends('admin.layout.main_admin')



@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header" style="padding:0px">
        @if (session('msg'))
        <div class="alert alert-success">
            {{ session('msg') }}
        </div>
        @endif
        <div class=" small-box bg-aqua" style="margin:0px">


            <div class="inner">
                <div class="text-right">
                    <span class="pull-left">
                        <h4>การแสดงผลของวิดีโอ :
                            @if($product->tc_video_platform == 0)
                            <i class="fa fa-vimeo "></i> Vimeo
                            @else
                            <i class="fa fa-youtube-play text-red"></i> Youtube

                            @endif
                        </h4>
                    </span>
                    <a href="{{ route('admin.section.show',$product_id) }}" class="btn  bg-orange btn-md">
                        <i class="fa fa-fw fa-plus"></i> เพิ่มบทเรียน
                    </a>
                </div>

            </div>
        </div>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12 connectedSortable " id="section_course">

                @foreach($sections as $sec)
                <!-- TO DO List -->
                <div class="box box-primary box-solid" id="section_{{ $sec->id }}">
                    <div class=" box-header">
                        <i class="fa fa-arrows"></i>

                        <h3 class="box-title">{{ $sec->sec_title }}</h3>
                        <h3 class="box-title pull-right">
                            <button class="btn btn-danger delete_section" section_id="{{$sec->id}}">
                                <i class="fa fa-fw fa-trash "></i> ลบบทเรียน
                            </button>

                            <a href="{{ route('admin.section.edit',$sec->id) }}" class="btn btn-success">
                                <i class="fa fa-fw fa-wrench "></i> แก้ไขหัวข้อบทเรียน
                            </a>
                            <a href="{{ route('admin.lecture.show',$sec->id) }}" class="btn btn-info">
                                <i class="fa fa-fw fa-plus"></i> สร้างวิดีโอบทเรียน
                            </a>
                        </h3>

                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <!-- See dist/js/pages/dashboard.js to activate the todoList plugin -->
                        <ul class="todo-list" id="todo">
                            @foreach($lectures as $lecture)
                            @if($lecture->lecture_section_id == $sec->id)
                            <li style="border-left:4px solid #00c0ef;" id="lecture_video_{{ $lecture->id }}">
                                <!-- drag handle -->
                                <span class="handle">
                                    <i class="fa fa-ellipsis-v"></i>
                                    <i class="fa fa-ellipsis-v"></i>
                                </span>

                                <!-- todo text -->
                                <span class="text">{{ $lecture->lecture_title}}</span>
                                <!-- Emphasis label -->
                                <!-- General tools such as edit or delete-->
                                <div class="tools" style="display:inline-block;">
                                    <a href="{{route('admin.lecture.edit',$lecture->id)}}">
                                        <i class="fa fa-edit" data-toggle="tooltip" data-placement="top"
                                            title="แก้ไขวิดีโอบทเรียน"></i>
                                    </a>
                                    <i class="fa fa-trash-o delete_lecture" lecture_id="{{$lecture->id}}"
                                        data-toggle="tooltip" data-placement="top" title="ลบวิดีโอบทเรียน">
                                    </i>
                                </div>
                            </li>
                            @endif
                            @endforeach
                        </ul>
                    </div>
                    <!-- /.box-body -->

                </div>
                <!-- /.box -->
                @endforeach
            </div>
        </div>

        <div class="alert-tab">
            <div class="alert-cart">
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <i class="icon fa fa-check"></i> <span id="alert-text">Save Success</span>
                </div>
            </div>
        </div>

    </section>
</div>

@endsection


@section('script')

<style>
.alert-tab {
    position: fixed;
    bottom: 50%;
    right: 1%;
    padding: 12px;
}

.alert-tab .alert-cart {
    position: fixed;
    bottom: 5%;
    right: 1%;
    display: none;
}
</style>
<script src="{{URL::asset('admin_backend/dist/js/pages/dashboard.js')}}"></script>

<script>
var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');

$.widget.bridge('uibutton', $.ui.button);

$("#section_course").sortable({
    update: function(e, ui) {
        var data = $(this).sortable('serialize');

        $.ajax({
            url: "/admin/section/sortSection",
            type: 'post',
            data: {
                _token: CSRF_TOKEN,
                data: data

            },
            success: function(result) {
                if (result.status == "OK") {

                    $('#alert-text').text("Section Save Success");
                    $('.alert-cart').fadeIn(1000);
                    setTimeout(function() {
                        $('.alert-cart').fadeOut(1000);
                    }, 4000);
                }
            },
            complete: function() {

            }
        });
    }

});

$(".todo-list").sortable({
    update: function(e, ui) {
        var data = $(this).sortable('serialize');
        console.log(data)

        $.ajax({
            url: "/admin/lecture/sortLecture",
            type: 'post',
            data: {
                _token: CSRF_TOKEN,
                data: data

            },
            success: function(result) {
                if (result.status == "OK") {
                    $('#alert-text').text("Lecture Save Success");
                    $('.alert-cart').fadeIn(1000);
                    setTimeout(function() {
                        $('.alert-cart').fadeOut(1000);
                    }, 4000);
                }

            },
            complete: function() {

            }
        });
    }
});

$(".delete_lecture").click(function(e) {
    var id = $(this).attr("lecture_id");
    if (confirm("คุณต้องการลบวิดีโอใช่หรือไม่ ?")) {
        console.log(id);
        $.ajax({
            type: "POST",
            url: "/admin/lecture/destroy",
            data: {
                _token: CSRF_TOKEN,
                id: id
            },
            dataType: 'JSON',
            success: function(data) {
                //console.log(data['data']);
                if (data['status'] == "success") {
                    $("#lecture_video_" + id).remove();

                    $('#alert-text').text("Lecture Delete Success");
                    $('.alert-cart').fadeIn(1000);
                    setTimeout(function() {
                        $('.alert-cart').fadeOut(1000);
                    }, 4000);
                }


            }
        });
    } else {
        e.preventDefault();
    }
});

$(".delete_section").click(function(e) {
    var id = $(this).attr("section_id");
    if (confirm("คุณต้องการลบบทเรียนใช่หรือไม่")) {
        // console.log(id);
        $.ajax({
            type: "POST",
            url: "/admin/section/destroy",
            data: {
                _token: CSRF_TOKEN,
                id: id
            },
            dataType: 'JSON',
            success: function(data) {
                //console.log(data['data']);
                if (data['status'] == "success") {
                    $("#section_" + id).remove();
                    $('#alert-text').text("Section Delete Success");
                    $('.alert-cart').fadeIn(1000);
                    setTimeout(function() {
                        $('.alert-cart').fadeOut(1000);
                    }, 4000);
                }

            }
        });
    } else {
        e.preventDefault();
    }
});
</script>

@endsection